 version: 2
 jobs:
   build:
     docker:
       - image: circleci/python:3.7.4
     steps:
       - checkout
       - run: git submodule sync
       - run: git submodule update --init
       - run: echo "testing circleci"
